issuer: https://token.actions.githubusercontent.com
subject_pattern: 'repo:jarrett-sandbox/npm-semantic-release:.*'

permissions:
  contents: write
  packages: write
  issues: write
  pull_requests: write